npx esbuild client/client.tsx \
    --watch \
    --bundle \
    --minify \
    --splitting \
    --sourcemap \
    --format=esm \
    --loader:.svg=dataurl \
    --loader:.woff2=dataurl \
    --target=es2022 \
    --outdir=bundle/client \
    --platform=browser
